# -*- coding: utf-8 -*-
"""pgm1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10p6CgsFMvh8MBIhRipJEU-LJybwvR4o4
"""

import numpy as np
array_from_list=np.array([1,2,3,4,5])
print("array from list",array_from_list)

array_with_range=np.arange(10)
print("array with range",array_with_range)

zeros_array=np.zeros((3,3))
print("array of zeros:\n",zeros_array)

ones_array=np.ones((2,5))
print("array of ones:\n",ones_array)

a=np.array([1,2,3])
b=np.array([4,5,6])

add_result=np.add(a,b)
print("addition:",add_result)

sub_result=np.subtract(a,b)
print("subtraction:",sub_result)

mul_result=np.multiply(a,b)
print("multiplication:",mul_result)

div_result=np.divide(a,b)
print("division:",div_result)