# -*- coding: utf-8 -*-
"""prgm5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10xPGeseo4DavBqrXUGZhTjfy93kZfamE
"""

import numpy as np
A = np.array([[2,1,-3],[3,0,1],[1,1,-1]])
b = np.array([-3,5,-2])
X = np.linalg.solve(A,b)
print("Matrix A:")
print(A)
print("Vector b:")
print(b)
print("Solution for X:")
print(X)

import matplotlib.pyplot as plt
X = [1,2,3,4,5]
Y = [2,3,5,7,11]
plt.plot(X,Y,marker='o')
plt.title('Line Plot')
plt.xlabel('X-axis')
plt.ylabel('Y-axis')
plt.show()

from logging import captureWarnings
import matplotlib.pyplot as plt
categories = ['A','B','C','D','E']
values = [4,7,1,8,5]
plt.bar(categories,values)
plt.xlabel('Categories')
plt.ylabel('Values')
plt.title('Simple Bar Plot')
plt.show()

import matplotlib.pyplot as plt
categories = ['A','B','C','D']
values = [5,7,3,8]
plt.bar(categories,values,color='purple')
plt.title('Bar Plot')
plt.xlabel('Categories')
plt.ylabel('Values')
plt.show()

import matplotlib.pyplot as plt
import numpy as np
data = np.random.randn(1000)
plt.hist(data,bins=30,color='blue',edgecolor='black')
plt.title('Hisitogram')
plt.xlabel('Value')
plt.ylabel('Frequency')
plt.show()

import matplotlib.pyplot as plt
x = [5,7,8,7,2,17,2,9,4,11,12,9,6]
y = [99,86,87,100,86,103,87,94,78,77,85,86,90]
plt.scatter(x,y,color='red')
plt.title('Scatter Plot')
plt.xlabel('X-axis')
plt.ylabel('Y-axis')
plt.show()