# -*- coding: utf-8 -*-
"""prgm2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WMLsECccd735rawMdhxQZL8xSy8Zu-Se
"""

import numpy as np
matrix1=np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix2=np.array([[9,8,7],[6,5,4],[3,2,1]])
matrix_sum=matrix1 + matrix2
matrix_diff=matrix1 - matrix2
matrix_product=matrix1 * matrix2
matrix_divide=matrix1 / matrix2
matrix_multiply=np.dot(matrix1,matrix2)
matrix1_transpose=np.transpose(matrix1)
diagonal_sum=np.trace(matrix1)
print("matrix1 :\n",matrix1)
print("matrix2 :\n",matrix2)
print("matrix Sum:\n",matrix_sum)
print("matrix Difference:\n",matrix_diff)
print("matrix Element-wise Product:\n",matrix_product)
print("matrix Element-wise Division:\n",matrix_divide)
print("matrix Multiplication:\n",matrix_multiply)
print("Transpose of Matrix 1:\n", matrix1_transpose)
print("Sum of Diagonal Element of Matrx 1:",diagonal_sum)

import numpy as np;
X = np.array([[1,2],[3,4]])
Y = np.array([[5,6],[7,8]])
print("Marix X is :\n",X)
print("Matrix Y is :\n",Y)
ap=np.power(X,2)
print("X^2=",ap)
result= ap + 2 * Y
print("X^2+2Y is \n",result)

import numpy as np
A = np.array([[2,1,-2],[3,0,1],[1,1,-1]])
b = np.array([-3,5,-2])
X = np.linalg.solve(A,b)
print("Matrix A:")
print(A)
print("Vector b:")
print(b)
print("Solution for X:")
print(X)