# -*- coding: utf-8 -*-
"""program10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PE68wcG2Sn9SRRb0XIO2EN7U5bpQL9EG
"""

import numpy as np
import pandas as pd

data = {'Name':['Tom', 'nick', 'krish', 'jack'],'Age':[20, 21, 19, 18]}
df = pd.DataFrame(data)
print(df)

data = {'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'], 'Age':[27, 24, 22, 32],
        'Address':['Delhi', 'Kanpur', 'Allahabad', 'Kannauj'],
        'Qualification':['Msc', 'MA', 'MCA', 'Phd']}
df = pd.DataFrame(data)
print(df[['Name', 'Qualification']])

data = pd.read_csv("emp2.csv")
data.info()

data.head()

first = data.head()
print(first)

arr=np.array([10,15,18,22])
s = pd.Series(arr)
print(s)

arr=np.array(['a','b','c','d'])
s=pd.Series(arr, index=['first','second','third','fourth'])
print(s)

s=pd.Series(50, index=[0, 1, 2, 3, 4])
print (s)

d={'Name': 'Deepthi', 'Class' : 'MCA', 'year' : 2014}
s=pd.Series(d)
print(s)

s = pd.Series([10,15,18,22])
df=pd.DataFrame(s)
df.columns=['List1']
df['List2']=20
df['List3']=df['List1']+df['List2']
print(df)

import matplotlib.pyplot as plt
np.random.seed(0)
values = np.random.randn(100)
s = pd.Series(values)
print("series\n",s)
s.plot(kind='hist', title='Normally distributed random values')
plt.show()

s.describe()

df = pd.DataFrame({'A': [1, 2, 1, 4, 3],
'B': [12, 14, 11, 16, 18],
'C': ['a', 'a', 'b', 'a', 'b']})
df

df.describe()

iris = pd.read_csv('/content/irisf.csv')
print(iris)

print(iris.head())

df = pd.DataFrame(pd.read_csv("/content/irisf.csv"))
df.hist()

iris['sepal.length'].hist()

import seaborn as sns
import matplotlib.pyplot as plt

data = sns.load_dataset('tips') # Scatter Plot
sns.scatterplot(x='total_bill', y='tip', data=data)
plt.title('Scatter Plot of Total Bill vs. Tip')
plt.xlabel('Total Bill')
plt.ylabel('Tip')
plt.show()

import pandas as pd
data = pd.read_csv ('california_house.csv')
data.info()
data.describe()
data.head()

import seaborn as sns
import matplotlib.pyplot as plt
data = pd.read_csv ('/content/housing.csv')

# data = sns.load_dataset('tips') # Scatter Plot
plt.figure(figsize=(10, 8))
sns.scatterplot(x='median_house_value', y='housing_median_age',data=data)
plt.title('Scatter Plot for Median House Value vs. Housing Median Age')
plt.xlabel('Median House Value')
plt.ylabel('Housing Median Age')
plt.show()

data = pd.read_csv ('/content/housing.csv')
plt.figure(figsize=(15, 10))
sns.boxplot(x='housing_median_age', y='median_house_value', data=data)
plt.title('Box Plot for Feature1 by Target')
plt.show()